<?php

namespace App\Controller\Admin;

use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\EmailField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserCrudController extends AbstractCrudController
{
    private $encoder;

    public function __construct(UserPasswordEncoderInterface $encoder)
    {
        $this->encoder = $encoder;
    }

    public static function getEntityFqcn(): string
    {
        return User::class;
    }

    public function configureFields(string $pageName): iterable
    {
        $list = [
            EmailField::new('email', 'Correo'),
            TextField::new('full_name', 'Nombres Completos'),
            ArrayField::new('roles', 'Rol')
        ];

        if (Crud::PAGE_NEW == $pageName) $list[] = TextField::new('password', 'Contraseña');
        return $list;
    }

    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {

        $entityInstance->setPassword($this->encoder->encodePassword($entityInstance, $entityInstance->getPassword()));
        parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }


}
